ansible_user: root
user_groups:
  - name: container-data
    gid: 1001
  - name: downloads
    gid: 1002
  - name: media
    gid: 1003
packages:
  - tmux
  - btop
cockpit_port: 443
usb_devices:
  - /dev/sda
  - /dev/sdb
container_data_label: container-data
container_data_subvolumes:
  - name: "@container-data"
    mount: "/var/srv/container-data"
  - name: "@container-data_snapshots"
    mount: "/var/srv/container-data/.snapshots"
container_data_owner: jmcdade
container_data_group: container-data
container_data_mode: '6770'
autofs_servers:
  - shares:
      - name: downloads
        uid: 1000
        gid: 1002
      - name: media
        uid: 1000
        gid: 1003
    name: homelab.kerbol.lan
    username: "{{ vault_kerbol_username }}"
    password: "{{ vault_kerbol_password }}"
