---
- name: Install Cockpit
  community.general.rpm_ostree_pkg:
    name: "{{ initial_setup_cockpit_packages }}"
    state: present
  notify: "Reboot host"

- name: Reboot host if needed
  ansible.builtin.meta: flush_handlers

- name: Ensure Cockpit socket is started and enabled
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: started
    enabled: true
    daemon_reload: true
  loop:
    - cockpit.socket

- name: Allow access to Cockpit
  ansible.posix.firewalld:
    service: cockpit
    permanent: true
    state: enabled
    immediate: true
