---
# tasks file for roles/initial-setup
- name: Remove kargs $ignition_firstboot from {{ inventory_hostname }}
  ansible.builtin.command:
    cmd: rpm-ostree kargs --delete-if-present='$ignition_firstboot' --unchanged-exit-77
  changed_when:
    - kargs_result.rc != 77
  failed_when:
    - kargs_result.rc != 0
    - kargs_result.rc != 77
  register: kargs_result
  notify: "Reboot host"

- name: Expand root filesystem
  ansible.builtin.include_tasks: expand_root.yml
  when: initial_setup_expand_root

- name: Create user
  ansible.builtin.include_tasks: create_user.yml
  when: initial_setup_create_user

- name: Update packages
  ansible.posix.rpm_ostree_upgrade:
  notify: "Reboot host"

- name: Install packages
  community.general.rpm_ostree_pkg:
    name: "{{ initial_setup_packages }}"
    state: present
  when:
    - initial_setup_packages is defined
  notify: "Reboot host"

- name: Configure btop
  ansible.builtin.include_tasks: config_btop.yml
  when: initial_setup_configure_btop

- name: Enable Cockpit
  ansible.builtin.include_tasks: enable_cockpit.yml
  when: initial_setup_enable_cockpit

- name: Reboot host if needed
  ansible.builtin.meta: flush_handlers
