FROM mcr.microsoft.com/devcontainers/base:bullseye

LABEL com.centurylinklabs.watchtower.enable="false"

RUN apt update &&\
    apt upgrade -y &&\
    apt install -y \
        apt-transport-https \
        ca-certificates \
        curl \
        pip &&\
    apt autoclean

RUN pip install --no-cache-dir \
        ansible \
        ansible-builder \
        ansible-lint \
        ansible-navigator \
        ansible-pylibssh

RUN mkdir -p /etc/apt/keyrings &&\
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key |\
        gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg &&\
    echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' |\
        tee /etc/apt/sources.list.d/kubernetes.list &&\
    apt update &&\
    apt install -y kubectl &&\
    apt autoclean