---
# tasks file for roles/mount-usbs
- name: Create btrfs filesystem
  ansible.builtin.include_tasks: create-btrfs.yml

- name: Mount and change security of filesystem
  ansible.builtin.include_tasks: mount-btrfs.yml
