---
- name: Mount filesystem
  ansible.posix.mount:
    path: "{{ mount_usbs_mountpoint }}"
    src: LABEL={{ mount_usbs_label }}
    fstype: btrfs
    opts: compress=zstd:3,nofail
    state: mounted

- name: Change permissions
  ansible.builtin.file:
    path: "{{ mount_usbs_mountpoint }}"
    owner: "{{ mount_usbs_owner }}"
    group: "{{ mount_usbs_group }}"
    mode: "{{ mount_usbs_mode }}"
    state: directory
