---
- name: Mount filesystem
  ansible.posix.mount:
    path: "{{ item.mount }}"
    src: LABEL={{ mount_usbs_label }}
    fstype: btrfs
    opts: subvol={{ item.name }},compress=zstd:3,nofail
    state: mounted
  loop: "{{ mount_usbs_subvolumes }}"

- name: Change permissions
  ansible.builtin.file:
    path: "{{ item.mount }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  loop: "{{ mount_usbs_subvolumes }}"

- name: Set SELinux file context
  community.general.sefcontext:
    target: "{{ item.mount }}(/.*)?"
    setype: "{{ item.setype }}"
  loop: "{{ mount_usbs_subvolumes }}"

- name: Apply SELinux file context
  ansible.builtin.command:
    cmd: restorecon -irv {{ item.mount }}
  register: restorecon_result
  changed_when: "'Relabeled' in restorecon_result.stdout"
  loop: "{{ mount_usbs_subvolumes }}"
